# Generated by Django 3.0.2 on 2020-01-27 13:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(max_length=10, unique=True, verbose_name='运输范围')),
                ('sort_code', models.IntegerField(verbose_name='显示排序')),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('Active', '有效')], max_length=6, verbose_name='状态')),
            ],
        ),
    ]
