# Generated by Django 3.0.2 on 2020-01-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0003_auto_20200127_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='保险公司')),
                ('contact', models.CharField(max_length=20, verbose_name='联系人')),
                ('telephone', models.CharField(max_length=100, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='联系人邮箱')),
            ],
            options={
                'verbose_name': '保险公司',
                'verbose_name_plural': '保险公司',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompanyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='费率')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsuranceCompany.InsuranceCompany', verbose_name='保险公司')),
                ('trans_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsuranceCompany.TransMap', verbose_name='运输范围与方式')),
            ],
            options={
                'verbose_name': '保险公司费率',
                'verbose_name_plural': '保险公司费率',
            },
        ),
    ]
