# Generated by Django 3.0.2 on 2020-01-28 15:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0004_insurancecompany_insurancecompanyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', '生效')], max_length=6, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='InsuranceCompanyMinPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='最低价')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsuranceCompany.InsuranceCompany', verbose_name='保险公司')),
                ('trans_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsuranceCompany.TransRange', verbose_name='运输范围')),
            ],
            options={
                'verbose_name': '保险公司最低价',
                'verbose_name_plural': '保险公司最低价',
            },
        ),
    ]
