# Generated by Django 3.0.2 on 2020-01-28 19:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0005_auto_20200128_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=20, unique=True, verbose_name='险种简称')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('insurance_text', models.CharField(max_length=500, verbose_name='险种内容')),
                ('insurance_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Main', '主险'), ('Additional', '附加险')], max_length=15, verbose_name='险种类别')),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', '生效')], max_length=6, verbose_name='状态')),
            ],
            options={
                'verbose_name': '险种',
                'verbose_name_plural': '险种',
            },
        ),
    ]
