# Generated by Django 3.0.2 on 2020-01-28 19:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0006_insurancepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Main', '主险'), ('Additional', '附加险')], max_length=15, verbose_name='险种类别'),
        ),
    ]
