# Generated by Django 3.0.2 on 2020-01-29 12:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0007_auto_20200128_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Active', '生效')], max_length=6, verbose_name='状态')),
                ('additional_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_insurance', to='InsuranceCompany.InsurancePolicy', verbose_name='附加险')),
                ('main_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_insurance', to='InsuranceCompany.InsurancePolicy', verbose_name='主险')),
                ('trans_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsuranceCompany.TransMap', verbose_name='运输范围与方式')),
            ],
            options={
                'verbose_name': '险种业务',
                'verbose_name_plural': '险种业务',
            },
        ),
    ]
