# Generated by Django 3.0.2 on 2020-01-31 14:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0009_auto_20200131_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('主险', '主险'), ('附加险', '附加险')], max_length=6, verbose_name='险种类别'),
        ),
    ]
