# Generated by Django 3.0.2 on 2020-02-01 14:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0011_auto_20200131_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Main', '主险'), ('Additional', '附加险')], max_length=15, verbose_name='险种类别'),
        ),
    ]
