# Generated by Django 3.0.2 on 2020-02-01 14:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0012_auto_20200201_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('有效', '有效')], max_length=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='insurance_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Main', '主险'), ('Additional', '附加险')], max_length=15, verbose_name='险种类别'),
        ),
    ]
