# Generated by Django 3.0.2 on 2020-02-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceCompany', '0014_auto_20200201_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transrange',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', '生效')], max_length=10, verbose_name='状态'),
        ),
    ]
